
services:
  # 1. База даних MySQL
  mysql_db:
    image: mysql:8.0
    container_name: sportstore_mysql
    restart: always
    environment:
      MYSQL_DATABASE: sportstore_db
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: support
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

# 1.1 брокер 
  # redis_broker:
  #   image: redis:7.2-alpine
  #   container_name: sportstore_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # 2. Бекенд (FastAPI)
  backend:
    build:
      context: ./02_back_end
      dockerfile: Dockerfile
    container_name: sportstore_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Прокидаємо код для Hot Reload
      - ./02_back_end:/app
    environment:
      DATABASE_URL: "mysql+pymysql://store_user:store_password@mysql_db:3306/sportstore_db"
    depends_on:
      - mysql_db
      # - redis_broker # Додаємо залежність

  # 3. Фронтенд (Next.js)
  frontend:
    build:
      context: ./01_front_end
      dockerfile: Dockerfile
    container_name: sportstore_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # Прокидаємо код для Hot Reload
      - ./01_front_end:/app
      # Захищаємо внутрішні модулі та кеш контейнера від затирання локальною папкою
      - /app/.next
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api"
    depends_on:
      - backend

volumes:
  mysql_data:
